"""empty message

Revision ID: b527960d3477
Revises: 
Create Date: 2022-08-22 15:03:31.187744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b527960d3477'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personalinfo',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('nib', sa.String(length=55), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=25), nullable=True),
    sa.Column('marital_status', sa.String(length=25), nullable=True),
    sa.Column('home_phone', sa.String(length=12), nullable=True),
    sa.Column('cell_phone', sa.String(length=12), nullable=True),
    sa.Column('work_phone', sa.String(length=12), nullable=True),
    sa.Column('street_address', sa.Text(), nullable=True),
    sa.Column('po_box', sa.String(length=55), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('employerinfo',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('employer_phone', sa.String(length=255), nullable=True),
    sa.Column('employer_street_address', sa.Text(), nullable=True),
    sa.Column('employer_po_box', sa.String(length=55), nullable=True),
    sa.Column('employer_city', sa.String(length=255), nullable=True),
    sa.Column('employer_country', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['personalinfo.record_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('kininfo',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('home_phone', sa.String(length=12), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('employer_phone', sa.String(length=255), nullable=True),
    sa.Column('employer_street_address', sa.Text(), nullable=True),
    sa.Column('employer_po_box', sa.String(length=55), nullable=True),
    sa.Column('employer_city', sa.String(length=255), nullable=True),
    sa.Column('employer_country', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['personalinfo.record_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kininfo')
    op.drop_table('employerinfo')
    op.drop_table('personalinfo')
    # ### end Alembic commands ###
