"""empty message

Revision ID: c69b6fe7dda5
Revises: f8c0267e160a
Create Date: 2022-09-07 20:44:08.766463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c69b6fe7dda5'
down_revision = 'f8c0267e160a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employerinfo', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('employerinfo', sa.Column('middle_name', sa.String(length=255), nullable=True))
    op.add_column('employerinfo', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('employerinfo', sa.Column('phone', sa.String(length=255), nullable=True))
    op.add_column('employerinfo', sa.Column('street_address', sa.Text(), nullable=True))
    op.add_column('employerinfo', sa.Column('po_box', sa.String(length=55), nullable=True))
    op.add_column('employerinfo', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('employerinfo', sa.Column('country', sa.Text(), nullable=True))
    op.drop_column('employerinfo', 'employer_phone')
    op.drop_column('employerinfo', 'employer_country')
    op.drop_column('employerinfo', 'employer_name')
    op.drop_column('employerinfo', 'employer_street_address')
    op.drop_column('employerinfo', 'employer_po_box')
    op.drop_column('employerinfo', 'employer_city')
    op.add_column('kininfo', sa.Column('street_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kininfo', 'street_address')
    op.add_column('employerinfo', sa.Column('employer_city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('employerinfo', sa.Column('employer_po_box', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=55), nullable=True))
    op.add_column('employerinfo', sa.Column('employer_street_address', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('employerinfo', sa.Column('employer_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('employerinfo', sa.Column('employer_country', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('employerinfo', sa.Column('employer_phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_column('employerinfo', 'country')
    op.drop_column('employerinfo', 'city')
    op.drop_column('employerinfo', 'po_box')
    op.drop_column('employerinfo', 'street_address')
    op.drop_column('employerinfo', 'phone')
    op.drop_column('employerinfo', 'last_name')
    op.drop_column('employerinfo', 'middle_name')
    op.drop_column('employerinfo', 'first_name')
    # ### end Alembic commands ###
